version: '3.8'

services:

    db:
        build: .docker/postgres
        container_name: link-jobs-db
        restart: always
        env_file:
            - .env
        tty: true
        ports:
            - 5432:5432
        volumes:
            - .docker/postgres/db:/var/lib/postgresql/data:z
        environment:
            - POSTGRES_DB=linkjobs
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=linkjobs
        networks:
            - app-network

    app:
        build: .
        container_name: link-jobs-app
        entrypoint: ./entrypoint.sh
        # entrypoint: dockerize -wait tcp://db:5432 -timeout 120s ./entrypoint.sh
        environment:
            - DB_HOST=db
            - DB_DATABASE=linkjobs
            - DB_USER=postgres
            - DB_PASS=linkjobs
        volumes:
            - .:/usr/app:z
            - /usr/app/node_modules
        ports:
            - 3333:3333
        networks:
            - app-network
        depends_on:
            - db

networks:
    app-network:
        driver: bridge